### PR TITLE
Attempt to fix cf-tool can't find

### PR DESCRIPTION
**Pull request by testitem**
I have literally zero knowledge of qt so I can't make a fancy dialog to ask the user what the cf-tool path is, but I think this *should* work on my system and most other systems. It's generally advised to put user binaries in /usr/local/bin and not /usr/bin anyways.

### CODE REVIEW

**Comment by ouuan** [comment]
This doesn't make sense since you can't force users to put the executable in `/usr/local/bin`, what's more it's not possible on Windows.

**Comment by coder3101** [comment]
With just one code changes, i will merge this PR, See how Open File opens a dialog and it returns a path. Allow user to choose CF path , its just 5-10 lines of code nothing fancy. Then we will help you how to make this changes to preferences dialog or possibly. @ouuan could do settings part and let you know.

**Comment by ouuan** [comment]
Why do you think all Mac users should put it in `/usr/local/bin`?

And you'd better not use anything from the std namespace, for `std::string`, use [QString](http://doc.qt.io/qt-5/qstring.html) instead.

**Comment by ouuan** [comment]
@coder3101 It's weird that the bot removed `change_requested` tag right after a new commit without reviewer's approve.

**Comment by coder3101** [comment]
I will re-request it. Please bear with bot, it was made by me long time ago when I was still learning Java script.

**Comment by testitem** [comment]
@ouuan because that's the only place in path you can put it into (you can't put it into `/usr/bin` since everything in `/usr` outside of `/usr/local` is locked, even to root)

**Comment by testitem** [comment]
wait what you made the bot

**Comment by ouuan** [comment]
> @ouuan because that's the only place in path you can put it into (you can't put it into `/usr/bin` since everything in `/usr` outside of `/usr/local` is locked, even to root)

OK then, I've never used Mac...

**Comment by ouuan** [comment]
@testitem To add a setting, you need to modify `ui/preferencewindow.ui`, `src/preferencewindow.cpp`, `include/SettingsManager.hpp`, `src/SettingsManager.cpp`, and apply the setting in `src/cftools.cpp`.

See cdabd44 for reference.

**Comment by testitem** [comment]
I'll get to it tomorrow, it's getting a bit late. But I think the branch is in a mergeable state.

**Comment by coder3101** [comment]
Resolved with 1a49958

It is recommended to please see how it is done to help and contribute in the project.

**Pull request closed without merging**
