### PR TITLE
feat: make file logic like Sublime

### PR DESCRIPTION
**Pull request by ouuan**
1. Open file when necessary instead of holding it.

2. Watch file changes on disk.

3. Show complete path when multiple tabs are of the same name.

4. Change language when saving unsaved files / saving as.

5. Text changes and other minor changes.

Please test these changes. I think there might be some bugs, especially when handling read/write file fails, and things related to problemURL.

### CODE REVIEW

**Comment by ouuan** [comment]
I'd like to reimplement runner/compiler/cf-tool related with #82 first, then implement #92, for fewer conflicts.

**Comment by coder3101** [comment]
Yes you are right, when i started the project i was not very aware of Qt API like QTemporaryFile. But Since now you have discovered it, it surely is nice to get rid of Base::Files because they can in future become a bottleneck and are not very portable. Let's Qt handle all cross platform things.

**Comment by coder3101** [comment]
I guess this is work in progress. So I will review it once you ask me to do so.

**Comment by ouuan** [comment]
> I guess this is work in progress. So I will review it once you ask me to do so.

I can also make a new PR and merge this to it, or work on #82 in this PR. But for a clean commit history, I'd like to have this PR merged first.

**Pull request merged**
