### PR TITLE
Fix CE on Mac

### PR DESCRIPTION
**Pull request by testitem**
RT

## Description
RT

## Related Issue
#129 

## Motivation and Context
RT

## How Has This Been Tested?
Tested on my computer

## Type of changes

- [x] Bug fix (a change which fixes an issue)
- [ ] New feature (a change which adds functionality)
- [ ] Documentation (a change which modifies the documentation only)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/coder3101/cp-editor/blob/master/CONTRIBUTING.md) document.
- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [x] I have used clang-format-9 and `.clang-format` file in the root directory to format my codes. I DIDN'T CHANGE THE FORMAT BUT I HONESTLY HATE CLANG-FORMAT, IT FORMATS ALL OF MY CODE INTO UGLY SPACES AND IN AN INCONSISTENT INDENTATION STYLE </rant>
- [x] The settings file in the old version can be used in the new version after this change.
- [x] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [x] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [x] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)

### CODE REVIEW

**Comment by testitem** [comment]
Why doesn't azure check mac, it would've prevented this

**Comment by ouuan** [comment]
Why should I check compiling on different OSs if the compile error is not caused by a `#ifdef Q_OS_XXX`? I'm writing C++ on Qt, not writing assembly.

**Comment by testitem** [comment]
- First of all, I'm asking why Azure doesn't do CI on a Mac system, not you. I know that not everyone has access to every kind of system, but at least the CI tester should.
 - can you just merge this trivial change

**Comment by ouuan** [comment]
Does 03b632e solve your problem?

**Comment by coder3101** [comment]
> * First of all, I'm asking why Azure doesn't do CI on a Mac system, not you. I know that not everyone has access to every kind of system, but at least the CI tester should.
> * can you just merge this trivial change

Hey before we roll out 6.0, CI will not only build application but also publish .DMG for installation, but it needs testing so wait till i upgrade to Mac Catalina, its 8 GB and I have no super fast free WiFi now.

**Comment by ouuan** [comment]
See <https://github.com/ouuan/cp-editor/commits/master>, let's use Github Actions instead of travis.ci, it's easy to test on multiple OSs and multiple versions of Qt.

**Comment by coder3101** [comment]
> See https://github.com/ouuan/cp-editor/commits/master, let's use Github Actions instead of travis.ci, it's easy to test on multiple OSs and multiple versions of Qt.

Cool Open a PR for it. Azure will also build but only release

**Comment by coder3101** [comment]
> > See https://github.com/ouuan/cp-editor/commits/master, let's use Github Actions instead of travis.ci, it's easy to test on multiple OSs and multiple versions of Qt.
> 
> Cool Open a PR for it. Azure will also build but only release

Creating PR will be bit difficult since you have some other changes too, I will manually do it just tell me, how to do it (set GitHub action)

**Comment by ouuan** [comment]
Closed in favor of a54a2cb. The old version failed on Github Actions checks but a54a2cb passed. Since you didn't reply, I think it fixed this bug.

**Pull request closed without merging**
